name: Feature Request

description: Suggest a new feature.

title: "[Feature] "

labels:
  - enhancement

body:

  - type: textarea

    id: proposal

    attributes:

      label: Proposal

    validations:

      required: true

  - type: textarea

    id: motivation

    attributes:

      label: Motivation

  - type: textarea

    id: alternatives

    attributes:

      label: Alternatives